FROM node:12.16.3

ARG USER=app

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN adduser --disabled-password --gecos '' $USER
COPY package.json /usr/src/app/package.json
COPY yarn.lock /usr/src/app/yarn.lock
RUN chown -R $USER:$USER /usr/src/app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

USER $USER
RUN yarn install

EXPOSE EEE

CMD /wait && yarn dev:watch
